Include sys/sysmacros.h for major() and minor()
Relying on sys/types.h is fatal since glibc 2.27 and was deprecated since
glibc 2.25.

Error was:

src/mod_path.c:176:19: error: called object ‘major’ is not a function or function pointer
    major = (long)major(st.st_rdev);
                  ^~~~~